name: smats CI

on:
  push:
    branches: [ main ]
    paths:
      - "smats/**"
      - "test/**"
  pull_request:
    branches: [ main ]
    paths:
      - "smats/**"
      - "test/**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: bazel build //smats

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Test
        run: bazel test //tests/...

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ubuntu-latest-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ubuntu-latest-bazel-

      - name: Lint
        run: bazel test //smats/...

  dwyu:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ubuntu-latest-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ubuntu-latest-bazel-

      - name: Test
        run: bazel build --config=dwyu //smats

  iwyu:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ubuntu-latest-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ubuntu-latest-bazel-

      - name: Test
        run:  CXX=clang bazel build --config=iwyu //smats/...
